version: "2.23.0-desktop.1"

services:
  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper

  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

  api-service:
    container_name: api-service
    build:
      context: .
      args:
        - APP=api-service
    depends_on:
      - kafka
      - redis
      - postgres
    environment:
      - KAFKA_HOST=zookeeper:2181
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"
    command: ["yarn", "run", "start:api-service"]
    volumes:
      - ./:/usr/src/app
    links:
      - zookeeper:zookeeper
      - redis:redis

  database-service:
    container_name: database-service
    build:
      context: .
      args:
        - APP=database-service
    depends_on:
      - kafka
      - redis
      - postgres
    environment:
      - KAFKA_HOST=zookeeper:2181
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: ["yarn", "run", "start:database-service"]
    volumes:
      - ./:/usr/src/app
    links:
      - zookeeper:zookeeper
      - redis:redis